export enum MENU_TYPE {
  USER_MENU = "UserMenu",
  PROJECT_MENU = "ProjectMenu",
  OPEN_PROJECT_MENU = "OpenProjectMenu",
  CREATE_PROJECT_MENU = "CreateProjectMenu",
  CLOSE_PROJECT_MENU = "CloseProjectMenu",
  IMPORT_PROJECT_FILE_MENU = "ImportProjectFile",
  EXPORT_PROJECT_FILE_MENU = "ExportProjectFile",
  IMPORT_LIBRARY_FILE_MENU = "ImportLibraryFile",
  EXPORT_LIBRARY_FILE_MENU = "ExportLibraryFile",
  COMMIT_PROJECT_MENU = "CommitProjectMenu",
  CREATE_SUB_PROJECT_MENU = "CreateSubProjectMenu",
  INSTRUCTION_PROJECT_MENU = "InstructionProjectMenu",
  VISUAL_FILTER_MENU = "VisualFilter",
  CONVERT_SUB_PROJECT_MENU = "ConvertSubProjectMenu",
}
