FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
 
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["ModelBuilder.Api/ModelBuilder.Api.csproj", "ModelBuilder.Api/"]
RUN dotnet restore "ModelBuilder.Api/ModelBuilder.Api.csproj"
COPY . .
WORKDIR "/src/ModelBuilder.Api"
RUN dotnet build "ModelBuilder.Api.csproj" -c Release -o /app/build
 
FROM build AS publish
RUN dotnet publish "ModelBuilder.Api.csproj" -c Release -o /app/publish
 
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ModelBuilder.Api.dll"]
