FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
 
FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["ModelBuilder/ModelBuilder.csproj", "ModelBuilder/"]
RUN dotnet restore "ModelBuilder/ModelBuilder.csproj"
COPY . .
WORKDIR "/src/ModelBuilder"
RUN dotnet build "ModelBuilder.csproj" -c Release -o /app/build
 
FROM build AS publish
RUN dotnet publish "ModelBuilder.csproj" -c Release -o /app/publish
 
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ModelBuilder.dll"]
