version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/src/client"
    schedule:
      interval: "daily"
      time: "09:30"
      timezone: "Europe/Oslo"
    target-branch: "julesprint"
    reviewers:
      - "henrik-knudsen"

  - package-ecosystem: "nuget"
    directory: "/src/service"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Oslo"
    target-branch: "julesprint"
    reviewers:
      - "kahovden"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:30"
      timezone: "Europe/Oslo"
    target-branch: "julesprint"
    reviewers:
      - "henrik-knudsen"
