version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/src/client"
    schedule:
      interval: "daily"
    target-branch: "julesprint"
    reviewers:
      - "henrik-knudsen"
    
  - package-ecosystem: "nuget"
    directory: "/src/service"
    schedule:
      interval: "daily"
    target-branch: "julesprint"
    reviewers:
      - "kahovden"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "julesprint"
    reviewers:
      - "henrik-knudsen"
