version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/src/client"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/Oslo"
    target-branch: "dev"
    reviewers:
      - "Bouvet-MatsAlmeland"

  - package-ecosystem: "nuget"
    directory: "/src/service"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/Oslo"
    target-branch: "dev"
    reviewers:
      - "Bouvet-MatsAlmeland"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/Oslo"
    target-branch: "dev"
    reviewers:
      - "Bouvet-MatsAlmeland"
