version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/src/client"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    target-branch: "julesprint"
    reviewees:
      - "mrlandro"
      - "henrik-knudsen"
      - "arisasel"
      - "fruithut"
    
  - package-ecosystem: "nuget"
    directory: "/src/service"
    schedule:
      interval: "daily"
    target-branch: "julesprint"
    reviewees:
      - "reliaboe"
      - "kahovden"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "julesprint"
    reviewees:
      - "henrik-knudsen"