const Color = {
  // Common
  WHITE: "#FFFFFF",
  BLACK: "#000000",
  BLUE_MAGENTA: "#272738",
  BLUE_DARK: "#1D2635",
  BLUE_LIGHT: "#D9E6FF",
  GREY: "#D9D9D9",
  GREY_DARK: "#C4C4C4",
  GREY_DARKER: "#898787",
  GREY_INACTIVE: "#8C8C8C",
  GREY_LIGHT: "#F2F2F2",
  GREY_LIGHTER: "#FBFBFF",
  GREY_HEADER: "#4F4F4F",
  GREY_INSPECTOR: "#FAFAFA",
  GREY_INSPECTOR_DISABLED: "#C5C5C5",
  GREY_TOOLBAR_SELECTED: "#6F6F6F",
  GREY_LIBRARY_INACTIVE_TAB: "#D4D4D4",
  GREY_LIBRARY_COLLECTION_BORDER: "#BCBCBC",

  CYAN_LIGHT: "#CFDADB",
  PURPLE_LIGHT: "#D8D8EC",
  RED_WARNING: "#FF708A",

  // Text
  TEXT_AVATAR: "#272838",

  // DarkMode
  DARKMODE_MAIN: "#888",
  DARKMODE_MODULE: "#A8A8A8",

  // Function aspect
  FUNCTION_MAIN: "#FEF445",
  FUNCTION_HEADER: "#FFFAA9",
  FUNCTION_TAB: "#FFDE7A",
  FUNCTION_SELECTED: "#FBC913",

  // Product aspect
  PRODUCT_MAIN: "#00F0FF",
  PRODUCT_HEADER: "#B9F5F9",
  PRODUCT_TAB: "#47DDE6",
  PRODUCT_SELECTED: "#069098",

  // Location aspect
  LOCATION_MAIN: "#FA00FF",
  LOCATION_HEADER: "#FDCCFE",
  LOCATION_TAB: "#F083F1",
  LOCATION_SELECTED: "#A300A7",

  // Terminals
  TRANSPORT_CONNECTION: "#606060",

  // Inspector
  INSPECTOR_DARK_BORDER: "#3D113F",

  // Inspector Parameters
  PARAMS_CYAN: "#65A8AD",
  PARAMS_CYAN_LIGHT: "#D9EAEB",
  PARAMS_PURPLE: "#8088FF",
  PARAMS_PURPLE_LIGHT: "#ECEDFD",
  PARAMS_PINK: "#D06BD4",
  PARAMS_PINK_LIGHT: "#F7DEF8",
  PARAMS_ORANGE: "#DF6A10",
  PARAMS_ORANGE_LIGHT: "#FFEEE1",
  PARAMS_GREEN: "#7A9F53",
  PARAMS_GREEN_LIGHT: "#DFF1CC",
  PARAMS_YELLOW: "#E3A814",
  PARAMS_YELLOW_LIGHT: "#FCF7C7",

  // Inspector Terminals
  TERMINALS_PURPLE: "#A5A5DC",
};

export default Color;
