// <auto-generated />
using System;
using Mb.Models.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mb.Core.Migrations
{
    [DbContext(typeof(ModelBuilderDbContext))]
    partial class ModelBuilderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AttributeType_Unit", b =>
                {
                    b.Property<string>("AttributeTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UnitId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AttributeTypeId", "UnitId");

                    b.HasIndex("UnitId");

                    b.ToTable("AttributeType_Unit", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.Attribute", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("AttributeTypeId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AttributeTypeId");

                    b.Property<string>("AttributeTypeIri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AttributeTypeIri");

                    b.Property<string>("Condition")
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)")
                        .HasColumnName("Condition");

                    b.Property<int>("Discipline")
                        .HasColumnType("int")
                        .HasColumnName("Discipline");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Entity");

                    b.Property<string>("Format")
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)")
                        .HasColumnName("Format");

                    b.Property<string>("InterfaceId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("InterfaceId");

                    b.Property<string>("InterfaceIri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InterfaceIri");

                    b.Property<string>("Iri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Iri");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsLocked");

                    b.Property<string>("IsLockedStatusBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IsLockedStatusBy");

                    b.Property<DateTime?>("IsLockedStatusDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("IsLockedStatusDate");

                    b.Property<string>("NodeId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("NodeId");

                    b.Property<string>("NodeIri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NodeIri");

                    b.Property<string>("Qualifier")
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)")
                        .HasColumnName("Qualifier");

                    b.Property<int>("SelectType")
                        .HasColumnType("int")
                        .HasColumnName("SelectType");

                    b.Property<string>("SelectValuesString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SelectValuesString");

                    b.Property<string>("SelectedUnitId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SelectedUnitId");

                    b.Property<string>("SimpleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SimpleId");

                    b.Property<string>("SimpleIri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SimpleIri");

                    b.Property<string>("Source")
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)")
                        .HasColumnName("Source");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tags");

                    b.Property<string>("TerminalId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TerminalId");

                    b.Property<string>("TerminalIri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TerminalIri");

                    b.Property<string>("TransportId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TransportId");

                    b.Property<string>("TransportIri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TransportIri");

                    b.Property<string>("UnitString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UnitString");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("InterfaceId");

                    b.HasIndex("NodeId");

                    b.HasIndex("SimpleId");

                    b.HasIndex("TerminalId");

                    b.HasIndex("TransportId");

                    b.ToTable("Attribute", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.CollaborationPartner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Current")
                        .HasColumnType("bit")
                        .HasColumnName("Current");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Domain");

                    b.Property<string>("Iris")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Iris");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("CollaborationPartner", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.Connector", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<int>("ConnectorVisibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ConnectorVisibility");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Iri");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsRequired");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("NodeId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("NodeId");

                    b.Property<string>("NodeIri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NodeIri");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Connector", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Connector");
                });

            modelBuilder.Entity("Mb.Models.Data.Edge", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("FromConnectorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FromConnectorId");

                    b.Property<string>("FromConnectorIri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FromConnectorIri");

                    b.Property<string>("FromNodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FromNodeId");

                    b.Property<string>("FromNodeIri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FromNodeIri");

                    b.Property<string>("InterfaceId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("InterfaceId");

                    b.Property<string>("Iri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Iri");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsLocked");

                    b.Property<string>("IsLockedStatusBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IsLockedStatusBy");

                    b.Property<DateTime?>("IsLockedStatusDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("IsLockedStatusDate");

                    b.Property<string>("MasterProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MasterProjectId");

                    b.Property<string>("MasterProjectIri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MasterProjectIri");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ProjectId");

                    b.Property<string>("ProjectIri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectIri");

                    b.Property<string>("ToConnectorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ToConnectorId");

                    b.Property<string>("ToConnectorIri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ToConnectorIri");

                    b.Property<string>("ToNodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ToNodeId");

                    b.Property<string>("ToNodeIri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ToNodeIri");

                    b.Property<string>("TransportId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TransportId");

                    b.HasKey("Id");

                    b.HasIndex("FromConnectorId");

                    b.HasIndex("FromNodeId");

                    b.HasIndex("InterfaceId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ToConnectorId");

                    b.HasIndex("ToNodeId");

                    b.HasIndex("TransportId");

                    b.ToTable("Edge", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.EnumBase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("Aspect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Aspect");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InternalType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ParentId");

                    b.Property<string>("SemanticReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SemanticReference");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Enum", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("EnumBase");
                });

            modelBuilder.Entity("Mb.Models.Data.Interface", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("Created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("InputTerminalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("InputTerminalId");

                    b.Property<string>("Iri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Iri");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Label");

                    b.Property<string>("LibraryTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LibraryTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("OutputTerminalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("OutputTerminalId");

                    b.Property<string>("Rds")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Rds");

                    b.Property<string>("SemanticReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SemanticReference");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("4590637F39B6BA6F39C74293BE9138DF")
                        .HasColumnName("StatusId");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("Version")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("1.0")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("InputTerminalId");

                    b.HasIndex("OutputTerminalId");

                    b.HasIndex("StatusId");

                    b.ToTable("Interface", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.Node", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("Aspect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Aspect");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("Created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("Height");

                    b.Property<string>("Iri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Iri");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsLocked");

                    b.Property<string>("IsLockedStatusBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IsLockedStatusBy");

                    b.Property<DateTime?>("IsLockedStatusDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("IsLockedStatusDate");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("bit")
                        .HasColumnName("IsRoot");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Label");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("Level");

                    b.Property<string>("LibraryTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LibraryTypeId");

                    b.Property<string>("MasterProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MasterProjectId");

                    b.Property<string>("MasterProjectIri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MasterProjectIri");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("Order");

                    b.Property<decimal>("PositionBlockX")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PositionBlockX");

                    b.Property<decimal>("PositionBlockY")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PositionBlockY");

                    b.Property<decimal>("PositionX")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PositionX");

                    b.Property<decimal>("PositionY")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PositionY");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ProjectId");

                    b.Property<string>("ProjectIri")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ProjectIri");

                    b.Property<string>("PurposeString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PurposeString");

                    b.Property<string>("Rds")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Rds");

                    b.Property<string>("SemanticReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SemanticReference");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("StatusId");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Symbol");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Version");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("Width");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectIri");

                    b.HasIndex("StatusId");

                    b.ToTable("Node", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.PredefinedAttribute", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Key");

                    b.Property<bool>("IsMultiSelect")
                        .HasColumnType("bit")
                        .HasColumnName("IsMultiSelect");

                    b.Property<string>("Values")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Values");

                    b.HasKey("Key");

                    b.ToTable("PredefinedAttribute", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Iri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Iri");

                    b.Property<bool>("IsSubProject")
                        .HasColumnType("bit")
                        .HasColumnName("IsSubProject");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("ProjectOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectOwner");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.Simple", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("Iri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Iri");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("NodeId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("NodeId");

                    b.Property<string>("NodeIri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NodeIri");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Simple", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.Transport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("Created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("InputTerminalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("InputTerminalId");

                    b.Property<string>("Iri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Iri");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Label");

                    b.Property<string>("LibraryTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LibraryTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("OutputTerminalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("OutputTerminalId");

                    b.Property<string>("Rds")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Rds");

                    b.Property<string>("SemanticReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SemanticReference");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("4590637F39B6BA6F39C74293BE9138DF")
                        .HasColumnName("StatusId");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("Version")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("1.0")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("InputTerminalId");

                    b.HasIndex("OutputTerminalId");

                    b.HasIndex("StatusId");

                    b.ToTable("Transport", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.AttributeType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("Aspect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Aspect");

                    b.Property<string>("ConditionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Discipline");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Entity");

                    b.Property<string>("FormatId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InterfaceTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QualifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SelectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SelectType");

                    b.Property<string>("SelectValuesString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SelectValuesString");

                    b.Property<string>("SourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tags");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.HasIndex("FormatId");

                    b.HasIndex("InterfaceTypeId");

                    b.HasIndex("QualifierId");

                    b.HasIndex("SourceId");

                    b.ToTable("AttributeType", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.BlobData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Discipline");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("BlobData", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.LibraryType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<int>("Aspect")
                        .HasColumnType("int");

                    b.Property<string>("BuildStatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc))
                        .HasColumnName("Created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("PurposeId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("PurposeId");

                    b.Property<string>("RdsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RdsId");

                    b.Property<string>("RdsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RdsName");

                    b.Property<string>("SemanticReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SemanticReference");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("4590637F39B6BA6F39C74293BE9138DF")
                        .HasColumnName("StatusId");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TypeId");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("BuildStatusId");

                    b.HasIndex("PurposeId");

                    b.ToTable("LibraryType", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("LibraryType");
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.NodeTypeTerminalType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConnectorType");

                    b.Property<string>("NodeTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Number");

                    b.Property<string>("TerminalTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NodeTypeId");

                    b.HasIndex("TerminalTypeId");

                    b.ToTable("NodeType_TerminalType", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.Rds", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("Iri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Iri");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Rds", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.SimpleType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("SemanticReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SemanticReference");

                    b.HasKey("Id");

                    b.ToTable("SimpleType", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.TerminalType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("TerminalCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TerminalCategoryId");

                    b.ToTable("TerminalType", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TypeId");

                    b.Property<string>("Ver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ver");

                    b.HasKey("Id");

                    b.ToTable("Version", (string)null);
                });

            modelBuilder.Entity("NodeType_AttributeType", b =>
                {
                    b.Property<string>("AttributeTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NodeTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AttributeTypeId", "NodeTypeId");

                    b.HasIndex("NodeTypeId");

                    b.ToTable("NodeType_AttributeType", (string)null);
                });

            modelBuilder.Entity("SimpleType_AttributeType", b =>
                {
                    b.Property<string>("AttributeTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SimpleTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AttributeTypeId", "SimpleTypeId");

                    b.HasIndex("SimpleTypeId");

                    b.ToTable("SimpleType_AttributeType", (string)null);
                });

            modelBuilder.Entity("SimpleType_NodeType", b =>
                {
                    b.Property<string>("NodeTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SimpleTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NodeTypeId", "SimpleTypeId");

                    b.HasIndex("SimpleTypeId");

                    b.ToTable("SimpleType_NodeType", (string)null);
                });

            modelBuilder.Entity("TerminalType_AttributeType", b =>
                {
                    b.Property<string>("AttributeTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TerminalTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AttributeTypeId", "TerminalTypeId");

                    b.HasIndex("TerminalTypeId");

                    b.ToTable("TerminalType_AttributeType", (string)null);
                });

            modelBuilder.Entity("TransportType_AttributeType", b =>
                {
                    b.Property<string>("AttributeTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransportTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AttributeTypeId", "TransportTypeId");

                    b.HasIndex("TransportTypeId");

                    b.ToTable("TransportType_AttributeType", (string)null);
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.AttributeCondition", b =>
                {
                    b.HasBaseType("Mb.Models.Data.Enums.EnumBase");

                    b.HasDiscriminator().HasValue("AttributeCondition");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.AttributeFormat", b =>
                {
                    b.HasBaseType("Mb.Models.Data.Enums.EnumBase");

                    b.HasDiscriminator().HasValue("AttributeFormat");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.AttributeQualifier", b =>
                {
                    b.HasBaseType("Mb.Models.Data.Enums.EnumBase");

                    b.HasDiscriminator().HasValue("AttributeQualifier");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.AttributeSource", b =>
                {
                    b.HasBaseType("Mb.Models.Data.Enums.EnumBase");

                    b.HasDiscriminator().HasValue("AttributeSource");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.BuildStatus", b =>
                {
                    b.HasBaseType("Mb.Models.Data.Enums.EnumBase");

                    b.HasDiscriminator().HasValue("BuildStatus");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.Purpose", b =>
                {
                    b.HasBaseType("Mb.Models.Data.Enums.EnumBase");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Discipline");

                    b.HasDiscriminator().HasValue("Purpose");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.TerminalCategory", b =>
                {
                    b.HasBaseType("Mb.Models.Data.Enums.EnumBase");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("TerminalCategory");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.TypeAttribute", b =>
                {
                    b.HasBaseType("Mb.Models.Data.Enums.EnumBase");

                    b.HasDiscriminator().HasValue("TypeAttribute");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.Unit", b =>
                {
                    b.HasBaseType("Mb.Models.Data.Enums.EnumBase");

                    b.HasDiscriminator().HasValue("Unit");
                });

            modelBuilder.Entity("Mb.Models.Data.Relation", b =>
                {
                    b.HasBaseType("Mb.Models.Data.Connector");

                    b.Property<int>("RelationType")
                        .HasColumnType("int")
                        .HasColumnName("RelationType");

                    b.HasDiscriminator().HasValue("Relation");
                });

            modelBuilder.Entity("Mb.Models.Data.Terminal", b =>
                {
                    b.HasBaseType("Mb.Models.Data.Connector");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalCategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TerminalCategoryId");

                    b.Property<string>("TerminalTypeId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TerminalTypeId");

                    b.Property<string>("TerminalTypeIri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TerminalTypeIri");

                    b.HasIndex("TerminalCategoryId");

                    b.HasDiscriminator().HasValue("Terminal");
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.InterfaceType", b =>
                {
                    b.HasBaseType("Mb.Models.Data.TypeEditor.LibraryType");

                    b.Property<string>("TerminalTypeId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("InterfaceType_TerminalTypeId");

                    b.HasIndex("TerminalTypeId");

                    b.HasDiscriminator().HasValue("InterfaceType");
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.NodeType", b =>
                {
                    b.HasBaseType("Mb.Models.Data.TypeEditor.LibraryType");

                    b.Property<string>("LocationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PredefinedAttributeData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymbolId")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("NodeType");
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.TransportType", b =>
                {
                    b.HasBaseType("Mb.Models.Data.TypeEditor.LibraryType");

                    b.Property<string>("TerminalTypeId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TransportType_TerminalTypeId");

                    b.HasIndex("TerminalTypeId");

                    b.HasDiscriminator().HasValue("TransportType");
                });

            modelBuilder.Entity("AttributeType_Unit", b =>
                {
                    b.HasOne("Mb.Models.Data.TypeEditor.AttributeType", null)
                        .WithMany()
                        .HasForeignKey("AttributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.Enums.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mb.Models.Data.Attribute", b =>
                {
                    b.HasOne("Mb.Models.Data.Interface", "Interface")
                        .WithMany("Attributes")
                        .HasForeignKey("InterfaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mb.Models.Data.Node", "Node")
                        .WithMany("Attributes")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mb.Models.Data.Simple", "Simple")
                        .WithMany("Attributes")
                        .HasForeignKey("SimpleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mb.Models.Data.Terminal", "Terminal")
                        .WithMany("Attributes")
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mb.Models.Data.Transport", "Transport")
                        .WithMany("Attributes")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Interface");

                    b.Navigation("Node");

                    b.Navigation("Simple");

                    b.Navigation("Terminal");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("Mb.Models.Data.Connector", b =>
                {
                    b.HasOne("Mb.Models.Data.Node", "Node")
                        .WithMany("Connectors")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Mb.Models.Data.Edge", b =>
                {
                    b.HasOne("Mb.Models.Data.Connector", "FromConnector")
                        .WithMany("FromEdges")
                        .HasForeignKey("FromConnectorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.Node", "FromNode")
                        .WithMany("FromEdges")
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.Interface", "Interface")
                        .WithMany("Edges")
                        .HasForeignKey("InterfaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mb.Models.Data.Project", "Project")
                        .WithMany("Edges")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.Connector", "ToConnector")
                        .WithMany("ToEdges")
                        .HasForeignKey("ToConnectorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.Node", "ToNode")
                        .WithMany("ToEdges")
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.Transport", "Transport")
                        .WithMany("Edges")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FromConnector");

                    b.Navigation("FromNode");

                    b.Navigation("Interface");

                    b.Navigation("Project");

                    b.Navigation("ToConnector");

                    b.Navigation("ToNode");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.EnumBase", b =>
                {
                    b.HasOne("Mb.Models.Data.Enums.EnumBase", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Mb.Models.Data.Interface", b =>
                {
                    b.HasOne("Mb.Models.Data.Terminal", "InputTerminal")
                        .WithMany("InputInterfaces")
                        .HasForeignKey("InputTerminalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.Terminal", "OutputTerminal")
                        .WithMany("OutputInterfaces")
                        .HasForeignKey("OutputTerminalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.Enums.BuildStatus", "Status")
                        .WithMany("Interfaces")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InputTerminal");

                    b.Navigation("OutputTerminal");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Mb.Models.Data.Node", b =>
                {
                    b.HasOne("Mb.Models.Data.Project", "Project")
                        .WithMany("Nodes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.Enums.BuildStatus", "Status")
                        .WithMany("Nodes")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Mb.Models.Data.Simple", b =>
                {
                    b.HasOne("Mb.Models.Data.Node", "Node")
                        .WithMany("Simples")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Mb.Models.Data.Transport", b =>
                {
                    b.HasOne("Mb.Models.Data.Terminal", "InputTerminal")
                        .WithMany("InputTransports")
                        .HasForeignKey("InputTerminalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.Terminal", "OutputTerminal")
                        .WithMany("OutputTransports")
                        .HasForeignKey("OutputTerminalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.Enums.BuildStatus", "Status")
                        .WithMany("Transports")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InputTerminal");

                    b.Navigation("OutputTerminal");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.AttributeType", b =>
                {
                    b.HasOne("Mb.Models.Data.Enums.AttributeCondition", "Condition")
                        .WithMany("AttributeTypes")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mb.Models.Data.Enums.AttributeFormat", "Format")
                        .WithMany("AttributeTypes")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mb.Models.Data.TypeEditor.InterfaceType", null)
                        .WithMany("AttributeTypes")
                        .HasForeignKey("InterfaceTypeId");

                    b.HasOne("Mb.Models.Data.Enums.AttributeQualifier", "Qualifier")
                        .WithMany("AttributeTypes")
                        .HasForeignKey("QualifierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mb.Models.Data.Enums.AttributeSource", "Source")
                        .WithMany("AttributeTypes")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Condition");

                    b.Navigation("Format");

                    b.Navigation("Qualifier");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.LibraryType", b =>
                {
                    b.HasOne("Mb.Models.Data.Enums.BuildStatus", null)
                        .WithMany("LibraryTypes")
                        .HasForeignKey("BuildStatusId");

                    b.HasOne("Mb.Models.Data.Enums.Purpose", "Purpose")
                        .WithMany("LibraryTypes")
                        .HasForeignKey("PurposeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Purpose");
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.NodeTypeTerminalType", b =>
                {
                    b.HasOne("Mb.Models.Data.TypeEditor.NodeType", "NodeType")
                        .WithMany("TerminalTypes")
                        .HasForeignKey("NodeTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mb.Models.Data.TypeEditor.TerminalType", "TerminalType")
                        .WithMany("NodeTypes")
                        .HasForeignKey("TerminalTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("NodeType");

                    b.Navigation("TerminalType");
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.TerminalType", b =>
                {
                    b.HasOne("Mb.Models.Data.Enums.TerminalCategory", "TerminalCategory")
                        .WithMany("TerminalTypes")
                        .HasForeignKey("TerminalCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TerminalCategory");
                });

            modelBuilder.Entity("NodeType_AttributeType", b =>
                {
                    b.HasOne("Mb.Models.Data.TypeEditor.AttributeType", null)
                        .WithMany()
                        .HasForeignKey("AttributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.TypeEditor.NodeType", null)
                        .WithMany()
                        .HasForeignKey("NodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleType_AttributeType", b =>
                {
                    b.HasOne("Mb.Models.Data.TypeEditor.AttributeType", null)
                        .WithMany()
                        .HasForeignKey("AttributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.TypeEditor.SimpleType", null)
                        .WithMany()
                        .HasForeignKey("SimpleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleType_NodeType", b =>
                {
                    b.HasOne("Mb.Models.Data.TypeEditor.NodeType", null)
                        .WithMany()
                        .HasForeignKey("NodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.TypeEditor.SimpleType", null)
                        .WithMany()
                        .HasForeignKey("SimpleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TerminalType_AttributeType", b =>
                {
                    b.HasOne("Mb.Models.Data.TypeEditor.AttributeType", null)
                        .WithMany()
                        .HasForeignKey("AttributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.TypeEditor.TerminalType", null)
                        .WithMany()
                        .HasForeignKey("TerminalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TransportType_AttributeType", b =>
                {
                    b.HasOne("Mb.Models.Data.TypeEditor.AttributeType", null)
                        .WithMany()
                        .HasForeignKey("AttributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mb.Models.Data.TypeEditor.TransportType", null)
                        .WithMany()
                        .HasForeignKey("TransportTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mb.Models.Data.Terminal", b =>
                {
                    b.HasOne("Mb.Models.Data.Enums.TerminalCategory", "TerminalCategory")
                        .WithMany("Terminals")
                        .HasForeignKey("TerminalCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerminalCategory");
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.InterfaceType", b =>
                {
                    b.HasOne("Mb.Models.Data.TypeEditor.TerminalType", "TerminalType")
                        .WithMany("InterfaceTypes")
                        .HasForeignKey("TerminalTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TerminalType");
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.TransportType", b =>
                {
                    b.HasOne("Mb.Models.Data.TypeEditor.TerminalType", "TerminalType")
                        .WithMany("TransportTypes")
                        .HasForeignKey("TerminalTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TerminalType");
                });

            modelBuilder.Entity("Mb.Models.Data.Connector", b =>
                {
                    b.Navigation("FromEdges");

                    b.Navigation("ToEdges");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.EnumBase", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Mb.Models.Data.Interface", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Edges");
                });

            modelBuilder.Entity("Mb.Models.Data.Node", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Connectors");

                    b.Navigation("FromEdges");

                    b.Navigation("Simples");

                    b.Navigation("ToEdges");
                });

            modelBuilder.Entity("Mb.Models.Data.Project", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Mb.Models.Data.Simple", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("Mb.Models.Data.Transport", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Edges");
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.TerminalType", b =>
                {
                    b.Navigation("InterfaceTypes");

                    b.Navigation("NodeTypes");

                    b.Navigation("TransportTypes");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.AttributeCondition", b =>
                {
                    b.Navigation("AttributeTypes");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.AttributeFormat", b =>
                {
                    b.Navigation("AttributeTypes");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.AttributeQualifier", b =>
                {
                    b.Navigation("AttributeTypes");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.AttributeSource", b =>
                {
                    b.Navigation("AttributeTypes");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.BuildStatus", b =>
                {
                    b.Navigation("Interfaces");

                    b.Navigation("LibraryTypes");

                    b.Navigation("Nodes");

                    b.Navigation("Transports");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.Purpose", b =>
                {
                    b.Navigation("LibraryTypes");
                });

            modelBuilder.Entity("Mb.Models.Data.Enums.TerminalCategory", b =>
                {
                    b.Navigation("TerminalTypes");

                    b.Navigation("Terminals");
                });

            modelBuilder.Entity("Mb.Models.Data.Terminal", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("InputInterfaces");

                    b.Navigation("InputTransports");

                    b.Navigation("OutputInterfaces");

                    b.Navigation("OutputTransports");
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.InterfaceType", b =>
                {
                    b.Navigation("AttributeTypes");
                });

            modelBuilder.Entity("Mb.Models.Data.TypeEditor.NodeType", b =>
                {
                    b.Navigation("TerminalTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
