//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBuilder.Rdf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelBuilder.Rdf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:allowedUnit.
        /// </summary>
        public static string AllowedUnit {
            get {
                return ResourceManager.GetString("AllowedUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:bidirectionalTerminal.
        /// </summary>
        public static string BidirectionalTerminal {
            get {
                return ResourceManager.GetString("BidirectionalTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:connectedTo.
        /// </summary>
        public static string ConnectedTo {
            get {
                return ResourceManager.GetString("ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:createdBy.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsd:dateTime.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:datumUOM.
        /// </summary>
        public static string DatumUOM {
            get {
                return ResourceManager.GetString("DatumUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:datumValue.
        /// </summary>
        public static string DatumValue {
            get {
                return ResourceManager.GetString("DatumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://rds.posccaesar.org/ontology/plm/rdl/PCA_100000510.
        /// </summary>
        public static string DefaultUom {
            get {
                return ResourceManager.GetString("DefaultUom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdfs:comment.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:domain.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsd:float.
        /// </summary>
        public static string Float {
            get {
                return ResourceManager.GetString("Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:FunctionalSystemBlock.
        /// </summary>
        public static string FSB {
            get {
                return ResourceManager.GetString("FSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:FunctionalSystemBlockTerminal.
        /// </summary>
        public static string FSBTerminal {
            get {
                return ResourceManager.GetString("FSBTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:fulfilledBy.
        /// </summary>
        public static string FulfilledBy {
            get {
                return ResourceManager.GetString("FulfilledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasAspect.
        /// </summary>
        public static string HasAspect {
            get {
                return ResourceManager.GetString("HasAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasAspectObjectFromConnection.
        /// </summary>
        public static string HasAspectObjectFromConnection {
            get {
                return ResourceManager.GetString("HasAspectObjectFromConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasAspectObjectToConnection.
        /// </summary>
        public static string HasAspectObjectToConnection {
            get {
                return ResourceManager.GetString("HasAspectObjectToConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasBidirectionalTerminal.
        /// </summary>
        public static string HasBidirectionalTerminal {
            get {
                return ResourceManager.GetString("HasBidirectionalTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasBlockPosX.
        /// </summary>
        public static string HasBlockPositionX {
            get {
                return ResourceManager.GetString("HasBlockPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasBlockPosY.
        /// </summary>
        public static string HasBlockPositionY {
            get {
                return ResourceManager.GetString("HasBlockPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasChild.
        /// </summary>
        public static string HasChild {
            get {
                return ResourceManager.GetString("HasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:color.
        /// </summary>
        public static string HasColor {
            get {
                return ResourceManager.GetString("HasColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:defaultFlowDirection.
        /// </summary>
        public static string HasDefaultFlowDirection {
            get {
                return ResourceManager.GetString("HasDefaultFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:discipline.
        /// </summary>
        public static string HasDiscipline {
            get {
                return ResourceManager.GetString("HasDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasHeight.
        /// </summary>
        public static string HasHeight {
            get {
                return ResourceManager.GetString("HasHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasInTerminal.
        /// </summary>
        public static string HasInputTerminal {
            get {
                return ResourceManager.GetString("HasInputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasLocation.
        /// </summary>
        public static string HasLocation {
            get {
                return ResourceManager.GetString("HasLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasMasterProject.
        /// </summary>
        public static string HasMasterProject {
            get {
                return ResourceManager.GetString("HasMasterProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasOutTerminal.
        /// </summary>
        public static string HasOutputTerminal {
            get {
                return ResourceManager.GetString("HasOutputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasOwner.
        /// </summary>
        public static string HasOwner {
            get {
                return ResourceManager.GetString("HasOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasParent.
        /// </summary>
        public static string HasParent {
            get {
                return ResourceManager.GetString("HasParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:hasPhysicalQuantity.
        /// </summary>
        public static string HasPhysicalQuantity {
            get {
                return ResourceManager.GetString("HasPhysicalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasPosX.
        /// </summary>
        public static string HasPositionX {
            get {
                return ResourceManager.GetString("HasPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasPosY.
        /// </summary>
        public static string HasPositionY {
            get {
                return ResourceManager.GetString("HasPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasPurpose.
        /// </summary>
        public static string HasPurpose {
            get {
                return ResourceManager.GetString("HasPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasSource.
        /// </summary>
        public static string HasSource {
            get {
                return ResourceManager.GetString("HasSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:symbol.
        /// </summary>
        public static string HasSymbol {
            get {
                return ResourceManager.GetString("HasSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasWidth.
        /// </summary>
        public static string HasWidth {
            get {
                return ResourceManager.GetString("HasWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:inTerminal.
        /// </summary>
        public static string InputTerminal {
            get {
                return ResourceManager.GetString("InputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsd:integer.
        /// </summary>
        public static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:IntegratedObject.
        /// </summary>
        public static string IntegratedObject {
            get {
                return ResourceManager.GetString("IntegratedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:isAspectOf.
        /// </summary>
        public static string IsAspectOf {
            get {
                return ResourceManager.GetString("IsAspectOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:isRequired.
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdfs:label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:lastUpdated.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:type.
        /// </summary>
        public static string LibraryType {
            get {
                return ResourceManager.GetString("LibraryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:rds.
        /// </summary>
        public static string MimirRds {
            get {
                return ResourceManager.GetString("MimirRds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:OutTerminal.
        /// </summary>
        public static string OutputTerminal {
            get {
                return ResourceManager.GetString("OutputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:PhysicalQuantity.
        /// </summary>
        public static string PhysicalQuantity {
            get {
                return ResourceManager.GetString("PhysicalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:qualityQuantifiedAs.
        /// </summary>
        public static string QualityQuantifiedAs {
            get {
                return ResourceManager.GetString("QualityQuantifiedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:rds.
        /// </summary>
        public static string RDS {
            get {
                return ResourceManager.GetString("RDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owl:sameAs.
        /// </summary>
        public static string SameAs {
            get {
                return ResourceManager.GetString("SameAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:ScalarQuantityDatum.
        /// </summary>
        public static string ScalarQuantityDatum {
            get {
                return ResourceManager.GetString("ScalarQuantityDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:Scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:selectType.
        /// </summary>
        public static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:selectValue.
        /// </summary>
        public static string SelectValue {
            get {
                return ResourceManager.GetString("SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:streamTerminal.
        /// </summary>
        public static string StreamTerminal {
            get {
                return ResourceManager.GetString("StreamTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdfs:subClassOf.
        /// </summary>
        public static string SubClassOf {
            get {
                return ResourceManager.GetString("SubClassOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:terminalDirection.
        /// </summary>
        public static string TerminalDirectionType {
            get {
                return ResourceManager.GetString("TerminalDirectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:Transmitter.
        /// </summary>
        public static string Transmitter {
            get {
                return ResourceManager.GetString("Transmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdf:type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:updatedBy.
        /// </summary>
        public static string UpdatedBy {
            get {
                return ResourceManager.GetString("UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owl:versionInfo.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:visibility.
        /// </summary>
        public static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
    }
}
