/**
 * Component for static size types in Mimir.
 */
const Size = {
  NODE_WIDTH: 160,
  NODE_HEIGHT: 95,

  BLOCK_NODE_WIDTH: 2430,
  BLOCK_NODE_HEIGHT: 1100,

  BLOCK_NODE_MIN_WIDTH: 2000,
  BLOCK_NODE_MIN_HEIGHT: 900,

  BLOCK_NODE_MAX_WIDTH: 3300,
  BLOCK_NODE_MAX_HEIGHT: 2000,

  BLOCK_MARGIN_Y: 70,
  BLOCK_MARGIN_X: 45,

  SPLITVIEW_DISTANCE: 120,
  SPLITVIEW_DIVISOR: 1.6,

  // Zoom
  ZOOM_DEFAULT: 1,
  ZOOM_SPLITVIEW: 0.7,

  // Modules
  MODULE_OPEN: 400,
  MODULE_CLOSED: 45,

  // Menus
  TOPMENU_HEIGHT: 54,

  // TypeEditor
  TYPEEDITOR_INSPECTOR_OPEN: 355, // TO BE REMOVED
  TYPEEDITOR_PROPERTIES_FULL_BASELINE: -362, // TO BE REMOVED
  TYPEEDITOR_PROPERTIES_SHRUNK_BASELINE: -672, // TO BE REMOVED
};

export default Size;
