export const Size = {
  // BlockView dimensions
  BLOCK_MARGIN_Y: 40,
  BLOCK_MARGIN_X: 250,
  BLOCK_SPLITVIEW_DIVISOR: 2.4,

  // Nodes
  BLOCK_CHILD_NODE_WIDTH: 160,
  BLOCK_CHILD_NODE_HEIGHT: 95,

  BLOCK_PARENT_WIDTH: window.innerWidth - 250,
  BLOCK_PARENT_HEIGHT: window.innerHeight - 140,
  BLOCK_PARENT_MAX_WIDTH: 2650,
  BLOCK_PARENT_MIN_WIDTH: 500,

  // Zoom
  DEFAULT_ZOOM_LEVEL: 1,

  // Modules
  MODULE_OPEN: 400,
  MODULE_CLOSED: 45,

  // Menus
  TOPMENU_HEIGHT: 54,

  // TypeEditor
  TYPEEDITOR_INSPECTOR_OPEN: 355, // TO BE REMOVED
  TYPEEDITOR_PROPERTIES_FULL_BASELINE: -362, // TO BE REMOVED
  TYPEEDITOR_PROPERTIES_SHRUNK_BASELINE: -672, // TO BE REMOVED
};
