//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdfParserModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RdfParserModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:allowedUnit.
        /// </summary>
        internal static string allowedUnit {
            get {
                return ResourceManager.GetString("allowedUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:Aspect.
        /// </summary>
        internal static string Aspect {
            get {
                return ResourceManager.GetString("Aspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:AspectObject.
        /// </summary>
        internal static string AspectObject {
            get {
                return ResourceManager.GetString("AspectObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:Attribute.
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:BiTerminal.
        /// </summary>
        internal static string BiTerminal {
            get {
                return ResourceManager.GetString("BiTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:connectedTo.
        /// </summary>
        internal static string connectedTo {
            get {
                return ResourceManager.GetString("connectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:context.
        /// </summary>
        internal static string context {
            get {
                return ResourceManager.GetString("context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eq:.
        /// </summary>
        internal static string equinorPrefix {
            get {
                return ResourceManager.GetString("equinorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:FunctionalSystemBlock.
        /// </summary>
        internal static string FSB {
            get {
                return ResourceManager.GetString("FSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:FunctionalSystemBlockTerminal.
        /// </summary>
        internal static string FSBTerminal {
            get {
                return ResourceManager.GetString("FSBTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:fulfilledBy.
        /// </summary>
        internal static string fulfilledBy {
            get {
                return ResourceManager.GetString("fulfilledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:Function.
        /// </summary>
        internal static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:FunctionAspectObject.
        /// </summary>
        internal static string FunctionAspectObject {
            get {
                return ResourceManager.GetString("FunctionAspectObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasActivity.
        /// </summary>
        internal static string hasActivity {
            get {
                return ResourceManager.GetString("hasActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasAspect.
        /// </summary>
        internal static string hasAspect {
            get {
                return ResourceManager.GetString("hasAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasAttribute.
        /// </summary>
        internal static string hasAttribute {
            get {
                return ResourceManager.GetString("hasAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasChild.
        /// </summary>
        internal static string hasChild {
            get {
                return ResourceManager.GetString("hasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasInputTerminal.
        /// </summary>
        internal static string hasInputTerminal {
            get {
                return ResourceManager.GetString("hasInputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasLocation.
        /// </summary>
        internal static string hasLocation {
            get {
                return ResourceManager.GetString("hasLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasOutputTerminal.
        /// </summary>
        internal static string hasOutputTerminal {
            get {
                return ResourceManager.GetString("hasOutputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasParent.
        /// </summary>
        internal static string hasParent {
            get {
                return ResourceManager.GetString("hasParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasTerminal.
        /// </summary>
        internal static string hasTerminal {
            get {
                return ResourceManager.GetString("hasTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasValue.
        /// </summary>
        internal static string hasValue {
            get {
                return ResourceManager.GetString("hasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:.
        /// </summary>
        internal static string imfPrefix {
            get {
                return ResourceManager.GetString("imfPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:InTerminal.
        /// </summary>
        internal static string InputTerminal {
            get {
                return ResourceManager.GetString("InputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:Installed.
        /// </summary>
        internal static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:installedAs.
        /// </summary>
        internal static string installedAs {
            get {
                return ResourceManager.GetString("installedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:InstalledAspectObject.
        /// </summary>
        internal static string InstalledAspectObject {
            get {
                return ResourceManager.GetString("InstalledAspectObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:IntegratedObject.
        /// </summary>
        internal static string IntegratedObject {
            get {
                return ResourceManager.GetString("IntegratedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:Interface.
        /// </summary>
        internal static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:isAspectOf.
        /// </summary>
        internal static string isAspectOf {
            get {
                return ResourceManager.GetString("isAspectOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdfs:label.
        /// </summary>
        internal static string label {
            get {
                return ResourceManager.GetString("label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:LocationAspectObject.
        /// </summary>
        internal static string LocationAspectObject {
            get {
                return ResourceManager.GetString("LocationAspectObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:.
        /// </summary>
        internal static string mimirPrefix {
            get {
                return ResourceManager.GetString("mimirPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:OutTerminal.
        /// </summary>
        internal static string OutputTerminal {
            get {
                return ResourceManager.GetString("OutputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:PrimaryAspect.
        /// </summary>
        internal static string PrimaryAspect {
            get {
                return ResourceManager.GetString("PrimaryAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:ProductAspectObject.
        /// </summary>
        internal static string ProductAspectObject {
            get {
                return ResourceManager.GetString("ProductAspectObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:Project.
        /// </summary>
        internal static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:RDSCodeIndex.
        /// </summary>
        internal static string RDSCodeIndex {
            get {
                return ResourceManager.GetString("RDSCodeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:RDSCodePrefix.
        /// </summary>
        internal static string RDSCodePrefix {
            get {
                return ResourceManager.GetString("RDSCodePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:SecondaryAspect.
        /// </summary>
        internal static string SecondaryAspect {
            get {
                return ResourceManager.GetString("SecondaryAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:selectedUnit.
        /// </summary>
        internal static string selectedUnit {
            get {
                return ResourceManager.GetString("selectedUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:StreamTerminal.
        /// </summary>
        internal static string StreamTerminal {
            get {
                return ResourceManager.GetString("StreamTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdfs:subClassOf.
        /// </summary>
        internal static string subClassOf {
            get {
                return ResourceManager.GetString("subClassOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:Terminal.
        /// </summary>
        internal static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:Transport.
        /// </summary>
        internal static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdf:type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
    }
}
