//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdfParserModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RdfParserModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:connectedTo.
        /// </summary>
        internal static string connectedTo {
            get {
                return ResourceManager.GetString("connectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:FunctionalSystemBlockTerminal.
        /// </summary>
        internal static string FSBTerminal {
            get {
                return ResourceManager.GetString("FSBTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:fulfilledBy.
        /// </summary>
        internal static string fulfilledBy {
            get {
                return ResourceManager.GetString("fulfilledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasActivity.
        /// </summary>
        internal static string hasActivity {
            get {
                return ResourceManager.GetString("hasActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasAspect.
        /// </summary>
        internal static string hasAspect {
            get {
                return ResourceManager.GetString("hasAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasChild.
        /// </summary>
        internal static string hasChild {
            get {
                return ResourceManager.GetString("hasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasLocation.
        /// </summary>
        internal static string hasLocation {
            get {
                return ResourceManager.GetString("hasLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasParent.
        /// </summary>
        internal static string hasParent {
            get {
                return ResourceManager.GetString("hasParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasTerminal.
        /// </summary>
        internal static string hasTerminal {
            get {
                return ResourceManager.GetString("hasTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:installedAs.
        /// </summary>
        internal static string installedAs {
            get {
                return ResourceManager.GetString("installedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:isAspectOf.
        /// </summary>
        internal static string isAspectOf {
            get {
                return ResourceManager.GetString("isAspectOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:RDSCodeIndex.
        /// </summary>
        internal static string RDSCodeIndex {
            get {
                return ResourceManager.GetString("RDSCodeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:RDSCodePrefix.
        /// </summary>
        internal static string RDSCodeSuffix {
            get {
                return ResourceManager.GetString("RDSCodeSuffix", resourceCulture);
            }
        }
    }
}
