//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdfParserModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RdfParserModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:allowedUnit.
        /// </summary>
        internal static string AllowedUnit {
            get {
                return ResourceManager.GetString("AllowedUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:connectedTo.
        /// </summary>
        internal static string ConnectedTo {
            get {
                return ResourceManager.GetString("ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:createdBy.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsd:dateTime.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:datumUOM.
        /// </summary>
        internal static string DatumUOM {
            get {
                return ResourceManager.GetString("DatumUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:datumValue.
        /// </summary>
        internal static string DatumValue {
            get {
                return ResourceManager.GetString("DatumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdfs:comment.
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:domain.
        /// </summary>
        internal static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsd:float.
        /// </summary>
        internal static string Float {
            get {
                return ResourceManager.GetString("Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:FunctionalSystemBlock.
        /// </summary>
        internal static string FSB {
            get {
                return ResourceManager.GetString("FSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:FunctionalSystemBlockTerminal.
        /// </summary>
        internal static string FSBTerminal {
            get {
                return ResourceManager.GetString("FSBTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:fulfilledBy.
        /// </summary>
        internal static string FulfilledBy {
            get {
                return ResourceManager.GetString("FulfilledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasAspect.
        /// </summary>
        internal static string HasAspect {
            get {
                return ResourceManager.GetString("HasAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasBlockPosX.
        /// </summary>
        internal static string HasBlockPositionX {
            get {
                return ResourceManager.GetString("HasBlockPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasBlockPosY.
        /// </summary>
        internal static string HasBlockPositionY {
            get {
                return ResourceManager.GetString("HasBlockPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasChild.
        /// </summary>
        internal static string HasChild {
            get {
                return ResourceManager.GetString("HasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:color.
        /// </summary>
        internal static string HasColor {
            get {
                return ResourceManager.GetString("HasColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:discipline.
        /// </summary>
        internal static string HasDiscipline {
            get {
                return ResourceManager.GetString("HasDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasInTerminal.
        /// </summary>
        internal static string HasInputTerminal {
            get {
                return ResourceManager.GetString("HasInputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasLocation.
        /// </summary>
        internal static string HasLocation {
            get {
                return ResourceManager.GetString("HasLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasMasterProject.
        /// </summary>
        internal static string HasMasterProject {
            get {
                return ResourceManager.GetString("HasMasterProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasNodeFromConnection.
        /// </summary>
        internal static string HasNodeFromConnection {
            get {
                return ResourceManager.GetString("HasNodeFromConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasNodeToConnection.
        /// </summary>
        internal static string HasNodeToConnection {
            get {
                return ResourceManager.GetString("HasNodeToConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasOutTerminal.
        /// </summary>
        internal static string HasOutputTerminal {
            get {
                return ResourceManager.GetString("HasOutputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasOwner.
        /// </summary>
        internal static string HasOwner {
            get {
                return ResourceManager.GetString("HasOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:hasParent.
        /// </summary>
        internal static string HasParent {
            get {
                return ResourceManager.GetString("HasParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:hasPhysicalQuantity.
        /// </summary>
        internal static string HasPhysicalQuantity {
            get {
                return ResourceManager.GetString("HasPhysicalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasPosX.
        /// </summary>
        internal static string HasPositionX {
            get {
                return ResourceManager.GetString("HasPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasPosY.
        /// </summary>
        internal static string HasPositionY {
            get {
                return ResourceManager.GetString("HasPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:hasPurpose.
        /// </summary>
        internal static string HasPurpose {
            get {
                return ResourceManager.GetString("HasPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:symbol.
        /// </summary>
        internal static string HasSymbol {
            get {
                return ResourceManager.GetString("HasSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:inTerminal.
        /// </summary>
        internal static string InputTerminal {
            get {
                return ResourceManager.GetString("InputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:integratedObject.
        /// </summary>
        internal static string IntegratedObject {
            get {
                return ResourceManager.GetString("IntegratedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:Interface.
        /// </summary>
        internal static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:isAspectOf.
        /// </summary>
        internal static string IsAspectOf {
            get {
                return ResourceManager.GetString("IsAspectOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:isRequired.
        /// </summary>
        internal static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdfs:label.
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:lastUpdated.
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:type.
        /// </summary>
        internal static string LibraryType {
            get {
                return ResourceManager.GetString("LibraryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:rds.
        /// </summary>
        internal static string MimirRds {
            get {
                return ResourceManager.GetString("MimirRds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:outTerminal.
        /// </summary>
        internal static string OutputTerminal {
            get {
                return ResourceManager.GetString("OutputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:PhysicalQuantity.
        /// </summary>
        internal static string PhysicalQuantity {
            get {
                return ResourceManager.GetString("PhysicalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:qualityQuantifiedAs.
        /// </summary>
        internal static string QualityQuantifiedAs {
            get {
                return ResourceManager.GetString("QualityQuantifiedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:rds.
        /// </summary>
        internal static string RDS {
            get {
                return ResourceManager.GetString("RDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:ScalarQuantityDatum.
        /// </summary>
        internal static string ScalarQuantityDatum {
            get {
                return ResourceManager.GetString("ScalarQuantityDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lis:Scale.
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:selectType.
        /// </summary>
        internal static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:selectValue.
        /// </summary>
        internal static string SelectValue {
            get {
                return ResourceManager.GetString("SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:streamTerminal.
        /// </summary>
        internal static string StreamTerminal {
            get {
                return ResourceManager.GetString("StreamTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdfs:subClassOf.
        /// </summary>
        internal static string SubClassOf {
            get {
                return ResourceManager.GetString("SubClassOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:terminalDirection.
        /// </summary>
        internal static string TerminalDirectionType {
            get {
                return ResourceManager.GetString("TerminalDirectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:Transmitter.
        /// </summary>
        internal static string Transmitter {
            get {
                return ResourceManager.GetString("Transmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:Transport.
        /// </summary>
        internal static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdf:type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imf:updatedBy.
        /// </summary>
        internal static string UpdatedBy {
            get {
                return ResourceManager.GetString("UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owl:versionInfo.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mimir:visibility.
        /// </summary>
        internal static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
    }
}
