/* All static text for TypeEditor */

export const TypeEditorTextResources = {
  TYPEEDITOR: "Type Editor",
  NEW_TYPE: "New Type",
  EDIT_TYPE: "Edit Type",
  ASPECT: "Aspect",
  OBJECT_TYPE: "Object Type",
  LOCATION_TYPE: "Location Type",
  PURPOSE: "Purpose",
  TYPE_NAME: "Type name",
  SYMBOL: "Symbol",
  PROPERTIES_RDS: "Choose or search RDS String...",
  PROPERTIES_TERMINALS: "Select or search Terminal Types...",
  PROPERTIES_TERMINAL_TYPE: "Search and choose Terminal Type...",
  PROPERTIES_ADD_TERMINAL: "Add",
  PROPERTIES_CLEAR_ALL_TERMINAL: "Clear all",
  PROPERTIES_PREDEFINED_LOCATION_ATTRIBUTES: "Select or search Predefined Location Attributes...",
  PROPERTIES_BLOCK_ATTRIBUTES: "Select or search Block Attributes...",
  PROPERTIES_LOCATION_ATTRIBUTES: "Select or search Location Attributes...",
  PROPERTIES_SIMPLE_TYPES: "Select or search Simple Types...",
  NEW_TYPE_PREVIEW: "Type Preview:",
  PREVIEW_INFO: "Click on preview objects to see inspector info",
  BUTTON_ADD: "Add to Library",
  BUTTON_EDIT: "Save Type Edit",
  BUTTON_CANCEL_ADD: "Cancel New Type",
  BUTTON_CANCEL_EDIT: "Cancel Edit",
  TYPE_PLACEHOLDER: "Write type name",
  ASPECT_PLACEHOLDER: "Choose Aspect",
  OBJECT_PLACEHOLDER: "Select Object Type",
  LOCATION_PLACEHOLDER: "Select Location Type",
  PURPOSE_PLACEHOLDER: "Select object purpose",
  SYMBOL_PLACEHOLDER: "Select object symbol",
  SEARCH: "Search or Select Terminal Media Type",
  ERROR_NAME: "*Please add a name for the type.",
  ERROR_ASPECT: "*Please select an aspect type.",
  ERROR_OBJECT_TYPE: "*Please select an object type.",
  ERROR_PURPOSE: "*Please select a purpose.",
  ERROR_SYMBOL: "*Please select a symbol.",
  ERROR_LOCATION_TYPE: "*Please select a location type.",
  ERROR_RDS: "*Please select RDS for the type.",
  ERROR_STATUS: "*Please select a status for the type",
  ERROR_ATTRIBUTES: "*Please add one or more attributes.",
  ERROR_LOCATION_ATTRIBUTES: "*Please add one or more location attributes.",
  ERROR_TERMINALS: "*Please select one or more terminal media types.",
  ERROR_TERMINALSTYPE: "*You can only select two of each terminal, one must be input, the other must be output.",
  ERROR_TERMINALS_INTERFACE: "*Please select a terminal type.",
  ERROR_SIMPLE_TYPES: "*Please select simple types.",
};
