
# Reusable workflow for building and pushing server app image.

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: The environment the client application will be deployed onto. Used for setting docker-tag.
    secrets:
      REGISTRY_SERVER_URL:
        required: true
        description: Server URL of docker image repository.
      REGISTRY_USERNAME:
        required: true
        description: Username to login onto docker image repository.
      REGISTRY_PASSWORD:
        required: true
        description: Password to login onto docker image repository.

jobs:
   # This workflow contains a single job called "build"
  build-server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/service

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}          
      - run: |
          docker build . -t ${{ secrets.REGISTRY_SERVER_URL }}/mimir-server:${{ inputs.environment }}
          docker push ${{ secrets.REGISTRY_SERVER_URL }}/mimir-server:${{ inputs.environment }}