# Reusable workflow for building and pushing client app image.

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: The environment the client application will be deployed onto.
      tag:
        required: true
        type: string
        description: Tag to use for docker image.
    secrets:
      REGISTRY_SERVER_URL:
        required: true
        description: Server URL of docker image repository.
      REGISTRY_USERNAME:
        required: true
        description: Username to login onto docker image repository.
      REGISTRY_PASSWORD:
        required: true
        description: Password to login onto docker image repository.

jobs:
  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/client
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}          
      - run: |
          docker build . -t ${{ secrets.REGISTRY_SERVER_URL }}/mimir-client:${{ inputs.tag }} --build-arg ENVIR=${{ inputs.environment }}
          docker push ${{ secrets.REGISTRY_SERVER_URL }}/mimir-client:${{ inputs.tag }}