name: Code Quality

on:
  pull_request:

  push:
    branches: [main, stage, demo, julesprint]

  workflow_dispatch:

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      client-changed: ${{ steps.changes.outputs.client }}
      server-changed: ${{ steps.changes.outputs.server }}
      docker-client-changed: ${{ steps.changes.outputs.docker-client }}
      docker-server-changed: ${{ steps.changes.outputs.docker-server }}
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.ref }}
          filters: .github/change-filters.yaml

  ######### CLIENT ###########

  code-quality-client-build:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.client-changed == 'true' }}
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: mimir-client
      context: ./src/client
      file: ./src/client/Dockerfile
      target: build
      hash_files_template: "**/package-lock.json"

  code-quality-client-test:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.client-changed == 'true' }}
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: mimir-client
      context: ./src/client
      file: ./src/client/Dockerfile
      target: test
      hash_files_template: "**/package-lock.json"

  code-quality-client-lint:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.client-changed == 'true' }}
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: mimir-client
      context: ./src/client
      file: ./src/client/Dockerfile
      target: lint
      hash_files_template: "**/package-lock.json"

  code-quality-client-format:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.client-changed == 'true' }}
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: mimir-client
      context: ./src/client
      file: ./src/client/Dockerfile
      target: format
      hash_files_template: "**/package-lock.json"

  ######### SERVER ###########

  code-quality-server-build:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.server-changed == 'true' }}
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: mimir-server
      context: ./src/service
      file: ./src/service/Dockerfile
      target: build
      hash_files_template: "**/*.csproj"
    secrets:
      REGISTRY_SERVER_URL: ${{secrets.REGISTRY_SERVER_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}

  code-quality-server-format:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.server-changed == 'true' }}
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: mimir-server
      context: ./src/service
      file: ./src/service/Dockerfile
      target: format
      hash_files_template: "**/*.csproj"
    secrets:
      REGISTRY_SERVER_URL: ${{secrets.REGISTRY_SERVER_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}

  ######### DOCKER ###########
