name: Code Quality

on:
  pull_request:
    
  push:
    branches: ["feature/ci-qa"]

  workflow_dispatch:

jobs:

  code-quality-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/client
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 13
          cache: "npm"
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        working-directory: src/client
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Lint
        working-directory: src/client
        run: npm run lint

      - name: Prettier
        working-directory: src/client
        run: npm run format:check  

      

      