name: Code Quality

on:
  pull_request:

  push:
    branches: [main, stage, demo, julesprint]

  workflow_dispatch:

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      client-changed: ${{ steps.changes.outputs.client }}
      server-changed: ${{ steps.changes.outputs.server }}
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.ref }}
          filters: .github/change-filters.yaml

  ######### CLIENT ###########

  code-quality-client-build:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.client-changed == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/client

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 13
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        working-directory: src/client
        run: npm ci

      - name: Build
        run: npm run build

  code-quality-client-test:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.client-changed == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/client

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 13
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        working-directory: src/client
        run: npm ci

      - name: Test
        run: npm test

  code-quality-client-lint:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.client-changed == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/client

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 13
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        working-directory: src/client
        run: npm ci

      - name: Lint
        working-directory: src/client
        run: npm run lint

  code-quality-client-format:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.client-changed == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/client

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 13
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        working-directory: src/client
        run: npm ci

      - name: Format
        working-directory: src/client
        run: npm run format:check

  ######### SERVER ###########

  code-quality-server-build-test:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.server-changed == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/service

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test  --no-restore --verbosity normal

  code-quality-server-format:
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.server-changed == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/service

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Format
        run: dotnet format . --verify-no-changes --verbosity diagnostic
