name: CI - DEV

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  construct-sha-short:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Set short commit sha as output.
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${GITHUB_SHA} | cut -c1-8)"

  build-client:
    needs: construct-sha-short
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: mimir-client
      build_args: |
        MIMIR_VERSION=dev-${{ needs.construct-sha-short.outputs.sha_short }}
      tags: dev
      context: ./src/client
      file: ./src/client/Dockerfile
      target: final
      hash_files_template: "**/package-lock.json"
      push: false

  build-server:
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: mimir-server
      tags: dev
      context: ./src/service
      file: ./src/service/Dockerfile
      target: final
      hash_files_template: "**/*.csproj"
      push: false
