name: CI - DEV

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ feature/sprint3 ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  environment: dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-client:
    uses: equinor/ti-spine-modelbuilder/.github/workflows/build-and-push-client.yaml@main
    with:
      environment: ${{env.environment}}
      tag: ${{env.environment}}
    secrets:
      REGISTRY_SERVER_URL: ${{secrets.REGISTRY_SERVER_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}

  build-server:
    uses: equinor/ti-spine-modelbuilder/.github/workflows/build-and-push-server.yaml@main
    with:
      tag: ${{env.environment}}
    secrets:
      REGISTRY_SERVER_URL: ${{secrets.REGISTRY_SERVER_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
      

