name: CI - PROD

on:
  push:
    branches: [ main ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
          tag_prefix: "v"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release  ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true

      - name: Check Output Parameters
        run: |
          echo "Tag: ${{ steps.release.outputs.new_tag }}"
          echo "Version: ${{ steps.release.outputs.new_version }}"

  build-client-latest:
    uses: equinor/ti-spine-modelbuilder/.github/workflows/partial.build-and-push-client.yaml@main
    needs: create-release
    if: ${{needs.create-release.outputs.tag!=''}}
    with:
      environment: prod
      tag: latest
    secrets:
      REGISTRY_SERVER_URL: ${{secrets.REGISTRY_SERVER_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}

  build-client-release:
    uses: equinor/ti-spine-modelbuilder/.github/workflows/partial.build-and-push-client.yaml@main
    needs: create-release
    if: ${{needs.create-release.outputs.tag!=''}}
    with:
      environment: prod
      tag: ${{needs.create-release.outputs.tag}}
    secrets:
      REGISTRY_SERVER_URL: ${{secrets.REGISTRY_SERVER_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}

  build-server-latest:
    uses: equinor/ti-spine-modelbuilder/.github/workflows/partial.build-and-push-server.yaml@main
    needs: create-release
    if: ${{needs.create-release.outputs.tag!=''}}
    with:
      tag: latest
    secrets:
      REGISTRY_SERVER_URL: ${{secrets.REGISTRY_SERVER_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}

  build-server-release:
    uses: equinor/ti-spine-modelbuilder/.github/workflows/partial.build-and-push-server.yaml@main
    needs: create-release
    if: ${{needs.create-release.outputs.tag!=''}}
    with:
      tag: ${{needs.create-release.outputs.tag}}
    secrets:
      REGISTRY_SERVER_URL: ${{secrets.REGISTRY_SERVER_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
          