name: CI - PROD

on:
  push:
    branches: [ main ]

jobs:
  create-release-new:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

  create-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag: ${{ steps.release.outputs.tag_name }}      
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          use_github_release_notes: true
          bump_version_scheme: minor
          tag_prefix: "v"
          
      - name: Check Output Parameters
        run: |
          echo "Tag: ${{ steps.release.outputs.tag_name }}"
          echo "Version: ${{ steps.release.outputs.version }}"
  build-client-latest:
    uses: equinor/ti-spine-modelbuilder/.github/workflows/partial.build-and-push-client.yaml@main
    needs: create-release
    if: ${{needs.create-release.outputs.tag!=''}}
    with:
      environment: prod
      tag: latest
    secrets:
      REGISTRY_SERVER_URL: ${{secrets.REGISTRY_SERVER_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}

  build-client-release:
    uses: equinor/ti-spine-modelbuilder/.github/workflows/partial.build-and-push-client.yaml@main
    needs: create-release
    if: ${{needs.create-release.outputs.tag!=''}}
    with:
      environment: prod
      tag: ${{needs.create-release.outputs.tag}}
    secrets:
      REGISTRY_SERVER_URL: ${{secrets.REGISTRY_SERVER_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}

  build-server-latest:
    uses: equinor/ti-spine-modelbuilder/.github/workflows/partial.build-and-push-server.yaml@main
    needs: create-release
    if: ${{needs.create-release.outputs.tag!=''}}
    with:
      tag: latest
    secrets:
      REGISTRY_SERVER_URL: ${{secrets.REGISTRY_SERVER_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}

  build-server-release:
    uses: equinor/ti-spine-modelbuilder/.github/workflows/partial.build-and-push-server.yaml@main
    needs: create-release
    if: ${{needs.create-release.outputs.tag!=''}}
    with:
      tag: ${{needs.create-release.outputs.tag}}
    secrets:
      REGISTRY_SERVER_URL: ${{secrets.REGISTRY_SERVER_URL}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
          