name: CI - Replace

on:
  workflow_dispatch:

jobs:
  replace-string:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.tag_replace.outputs.value }}      
    steps:
      - name: Find & Replace
        id: tag_replace        
        with:
          script: |
            let str = "4.0.0-RC.1";
            value = str.replace(/\.(?=[^.]*$)/, "");
            console.log(value);
      - name: Print Result
        run: echo "${{ steps.tag_replace.outputs.value }}"
        
