name: CI - STAGE

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [stage]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-client:
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: mimir-client
      tags: stage
      context: ./src/client
      file: ./src/client/Dockerfile
      target: final
      hash_files_template: "**/package-lock.json"
      push: true
    secrets:
      REGISTRY_SERVER_URLS: ${{ secrets.REGISTRY_SERVER_URL }}
      REGISTRY_USERNAMES: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORDS: ${{ secrets.REGISTRY_PASSWORD }}

  build-server:
    uses: mimir-org/mimir-actions/.github/workflows/docker-build-push-cached.yaml@main
    with:
      repository: mimir-server
      tags: stage
      context: ./src/service
      file: ./src/service/Dockerfile
      target: final
      hash_files_template: "**/*.csproj"
      push: true
    secrets:
      REGISTRY_SERVER_URLS: ${{ secrets.REGISTRY_SERVER_URL }}
      REGISTRY_USERNAMES: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORDS: ${{ secrets.REGISTRY_PASSWORD }}
